import {
  Result,
  ZonedDateTime,
  combineAll,
  fail,
  ok,
} from '@creativo/domain/kernel';
import {
  Identifier,
  IdentifierInput,
  createIdentifier,
  reconstituteIdentifier,
} from './identifier';
import { OtpId } from './ids';
import {
  EmptyCodeHashError,
  EmptySaltError,
  InvalidMaxAttemptsError,
  IssueOtpError,
  OtpVerificationError,
} from './otp.errors';

/** UTC throughout — these are internal system instants, not user-facing local wall-clock times. */
const OTP_ZONE = 'UTC';

export interface IssueOtpProps {
  id: string;
  identifier: IdentifierInput;
  /** Already computed by a (future, Goal-03-owned) `OtpCodeHasher` port — this entity never hashes anything itself. */
  codeHash: string;
  /** Already generated by a (future, Goal-03-owned) `OtpCodeGenerator` port. */
  salt: string;
  maxAttempts: number;
  ttlMinutes: number;
}

export interface ReconstituteOtpProps {
  id: string;
  identifier: IdentifierInput;
  codeHash: string;
  salt: string;
  expiresAtIso: string;
  attemptCount: number;
  maxAttempts: number;
  consumedAtIso: string | null;
  createdAtIso: string;
}

/**
 * An in-flight (or resolved) OTP challenge against an `Identifier`.
 *
 * **Deliberate Goal-02 deviation from this repo's existing
 * `libs/domain/models/otp.ts`**: that entity's `issue()`/`verify()` take
 * `OtpCodeGenerator`/`OtpCodeHasher` PORTS as parameters, because OTP
 * hashing needs `node:crypto`. This `domain/identity` pass is pure-domain,
 * zero-port TypeScript — no port interfaces are defined or imported here.
 * Instead:
 *   - `issue()` takes the ALREADY-COMPUTED `codeHash`/`salt` as plain
 *     inputs — a future application-layer use case owns the crypto ports,
 *     generates the raw code + salt, hashes it, and passes the hash in.
 *   - `verify()` takes a pre-computed boolean (`codeMatches` — "does the
 *     hash the caller already computed with its own hasher port match
 *     `this.codeHash`") instead of a raw code + a hasher port. This
 *     entity's job is purely the state-machine logic: consumed? expired?
 *     locked out? otherwise branch on `codeMatches`.
 */
export class Otp {
  private constructor(
    readonly id: OtpId,
    readonly identifier: Identifier,
    readonly codeHash: string,
    readonly salt: string,
    readonly expiresAt: ZonedDateTime,
    readonly attemptCount: number,
    readonly maxAttempts: number,
    readonly consumedAt: ZonedDateTime | null,
    readonly createdAt: ZonedDateTime,
  ) {}

  static issue(
    props: IssueOtpProps,
    now: ZonedDateTime,
  ): Result<Otp, IssueOtpError[]> {
    const idResult = OtpId.create(props.id);
    const identifierResult = createIdentifier(props.identifier);
    const codeHashResult = Otp.validateCodeHash(props.codeHash);
    const saltResult = Otp.validateSalt(props.salt);
    const maxAttemptsResult = Otp.validateMaxAttempts(props.maxAttempts);
    const expiresAtResult = ZonedDateTime.fromISO(
      now.plusMinutes(props.ttlMinutes).toISO(),
      OTP_ZONE,
    );

    const combined = combineAll([
      idResult,
      identifierResult,
      codeHashResult,
      saltResult,
      maxAttemptsResult,
      expiresAtResult,
    ] as const);
    if (combined.isFailure()) {
      return fail(combined.error);
    }
    const [id, identifier, codeHash, salt, maxAttempts, expiresAt] =
      combined.value;

    return ok(
      new Otp(
        id,
        identifier,
        codeHash,
        salt,
        expiresAt,
        0,
        maxAttempts,
        null,
        now,
      ),
    );
  }

  static reconstitute(
    props: ReconstituteOtpProps,
  ): Result<Otp, IssueOtpError[]> {
    const idResult = OtpId.create(props.id);
    const codeHashResult = Otp.validateCodeHash(props.codeHash);
    const saltResult = Otp.validateSalt(props.salt);
    const maxAttemptsResult = Otp.validateMaxAttempts(props.maxAttempts);
    const expiresAtResult = ZonedDateTime.fromISO(props.expiresAtIso, OTP_ZONE);
    const createdAtResult = ZonedDateTime.fromISO(props.createdAtIso, OTP_ZONE);

    const combined = combineAll([
      idResult,
      codeHashResult,
      saltResult,
      maxAttemptsResult,
      expiresAtResult,
      createdAtResult,
    ] as const);
    if (combined.isFailure()) {
      return fail(combined.error);
    }
    const [id, codeHash, salt, maxAttempts, expiresAt, createdAt] =
      combined.value;

    const identifier = reconstituteIdentifier(props.identifier);

    let consumedAt: ZonedDateTime | null = null;
    if (props.consumedAtIso) {
      const consumedAtResult = ZonedDateTime.fromISO(
        props.consumedAtIso,
        OTP_ZONE,
      );
      if (consumedAtResult.isFailure()) {
        return fail([consumedAtResult.error]);
      }
      consumedAt = consumedAtResult.value;
    }

    return ok(
      new Otp(
        id,
        identifier,
        codeHash,
        salt,
        expiresAt,
        props.attemptCount,
        maxAttempts,
        consumedAt,
        createdAt,
      ),
    );
  }

  /**
   * Pure state-machine check — never mutates. `codeMatches` is the
   * pre-computed result of the caller's own hasher-port comparison; a
   * `false` value is reported as `{kind: 'wrong_code'}` WITHOUT touching
   * `attemptCount` — the caller explicitly calls `recordFailedAttempt()`
   * and persists that, since "the code was wrong" is a use-case-level
   * decision about what to do next, not something pure verification
   * should silently bundle in.
   */
  verify(
    codeMatches: boolean,
    now: ZonedDateTime,
  ): Result<Otp, OtpVerificationError> {
    if (this.consumedAt) {
      return fail({ kind: 'already_consumed' });
    }
    if (now.isAfter(this.expiresAt)) {
      return fail({ kind: 'expired' });
    }
    if (this.attemptCount >= this.maxAttempts) {
      return fail({ kind: 'locked_out' });
    }
    if (!codeMatches) {
      return fail({ kind: 'wrong_code' });
    }
    return ok(this.withConsumedAt(now));
  }

  /** Explicit, separate mutation — the use-case calls this after a `verify()` failure with `kind: 'wrong_code'` so the incremented attempt count gets persisted. */
  recordFailedAttempt(): Otp {
    return this.withAttemptCount(this.attemptCount + 1);
  }

  private static validateCodeHash(
    raw: string,
  ): Result<string, EmptyCodeHashError> {
    const trimmed = raw.trim();
    return trimmed.length > 0 ? ok(trimmed) : fail(new EmptyCodeHashError());
  }

  private static validateSalt(raw: string): Result<string, EmptySaltError> {
    const trimmed = raw.trim();
    return trimmed.length > 0 ? ok(trimmed) : fail(new EmptySaltError());
  }

  private static validateMaxAttempts(
    raw: number,
  ): Result<number, InvalidMaxAttemptsError> {
    return Number.isInteger(raw) && raw > 0
      ? ok(raw)
      : fail(new InvalidMaxAttemptsError(raw));
  }

  private withConsumedAt(consumedAt: ZonedDateTime): Otp {
    return new Otp(
      this.id,
      this.identifier,
      this.codeHash,
      this.salt,
      this.expiresAt,
      this.attemptCount,
      this.maxAttempts,
      consumedAt,
      this.createdAt,
    );
  }

  private withAttemptCount(attemptCount: number): Otp {
    return new Otp(
      this.id,
      this.identifier,
      this.codeHash,
      this.salt,
      this.expiresAt,
      attemptCount,
      this.maxAttempts,
      this.consumedAt,
      this.createdAt,
    );
  }
}
